# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Artem Misko
  description: Role for install compose-app in docker container
  license: MIT

  min_ansible_version: "12"

  galaxy_tags: []

dependencies: []
